name: CosmosExamplePlugin
version: '${version}'
main: me.illusion.example.cosmosexampleplugin.CosmosExamplePlugin
api-version: 1.19

depend:
  - Cosmos
commands:
  createarena:
  pastearena:
  removearena:
  removeall: